### ISSUE TITLE
TypeError: split() takes no keyword arguments

### ISSUE THREAD

**Issue by davidmoate88** [bigtreetech/Eddy#33]
Klipper errors after installing Eddy USB. 

`probe_eddy_current btt_eddy: No drift calibration configured, disabling temperature compensation
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/probe_eddy_current.py", line 868, in load_config_prefix
    return PrinterEddyProbe(config)
  File "/home/pi/klipper/klippy/extras/probe_eddy_current.py", line 333, in __init__
    self.calibration = EddyCalibration(config)
  File "/home/pi/klipper/klippy/extras/probe_eddy_current.py", line 16, in __init__
    self.drift_comp = EddyDriftCompensation(config)
  File "/home/pi/klipper/klippy/extras/probe_eddy_current.py", line 393, in __init__
    temp_section = "temperature_probe " + self.name.split(maxsplit=1)[-1]
TypeError: split() takes no keyword arguments`

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out.
Please refer the instruction video to set up the eddy https://bttwiki.com/Eddy.html
Our support team does not operate using the GitHub platform 
but we would be happy to help you via email based ticketing system. Please visit
https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
